[build]
  command = "npm run build"
  publish = "build"
  environment = [
    "REACT_APP_API_URL"
  ]

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200